name: Validate PR
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "development" ]
jobs:
  check_formatting:
    runs-on: windows-latest
    name: Check Formatting
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3.3.0
    - name: 'validate'
      run: |
        dotnet tool restore
        dotnet csharpier --check .
