name: Validate PR
on:
  push:
jobs:
  check_formatting:
    runs-on: windows-latest
    name: Check Formatting
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
    - name: 'validate'
      run: |
        dotnet tool restore
        dotnet csharpier --check .
